#!/bin/sh

# Faces
none='\033[0m'
green='\033[32m'

export application=$PWD/bin/chrome-shell
for platform do
  . "./scripts/$platform-target.sh"
  mkdir -p "$TARGET"
  printf "${green}Installing${none}: %s\n" "$TARGET/shell.json"
  jq '.path = env.application' shell.json > "$TARGET/shell.json"
done
